identify_city:
  description: >
    Given the origin city {origin}, a list of potential destinations, including {cities}, interests: {interests} and Travel Date: {travel_dates}, 
    please analyze and select the best city for the trip based on specific 
    criteria such as weather patterns, seasonal events, and travel costs. 
    This task involves comparing multiple cities, considering factors like current weather 
    conditions, upcoming cultural or seasonal events, and overall travel expenses. 

    Your final answer must be a detailed report on the chosen city, 
    and everything you found out about it, including the actual flight costs, weather forecast and attractions.
  expected_output: >
    A detailed report on the chosen city, including actual flight costs, weather forecast, and attractions.
  agent: city_selection_expert

gather_city_info:
  description: >
    As a local expert on the selected city you must compile an in-depth guide for someone traveling there and wanting 
    to have THE BEST trip ever! Gather information about key attractions, local customs, special events, 
    and daily activity recommendations. Find the best spots to go to, the kind of place only a local would know.
    This guide should provide a thorough overview of what the city has to offer, including hidden gems, cultural
    hotspots, must-visit landmarks, weather forecasts, and high level costs.

    Your final answer must be a comprehensive city guide, rich in cultural insights and practical tips, 
    tailored to enhance the travel experience.
  expected_output: >
    A detailed report on the chosen city, including actual flight costs, weather forecast, and attractions.
  agent: local_tour_guide

plan_itinerary:  
  description: >
    Given the destination city being chosen, the dates to travel as {travel_dates}, and the travel interests as {travel_interests}, 
    expand the city guide into a full 7-day travel itinerary with detailed per-day plans, 
    including weather forecasts, places to eat, packing suggestions, and a budget breakdown. 
    You MUST suggest actual places to visit, actual hotels to stay, and actual restaurants to go to. 
    This itinerary should cover all aspects of the trip, from arrival to departure, integrating the city guide information with practical travel logistics.
    
    Your final answer MUST be a complete expanded travel plan, formatted as markdown, encompassing a daily schedule,
    anticipated weather conditions, recommended clothing and items to pack, and a detailed budget, ensuring THE BEST
    TRIP EVER. Be specific and give it a reason why you picked each place, what makes them special! 
  expected_output: >
    Complete expanded travel plan with daily schedule, weather conditions, packing suggestions, and budget breakdown
  agent: expert_travel_agent


